apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: util-common-service
spec:
  selector:
    matchLabels:
      app: util-common-service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: util-common-service
    spec:
      containers:
        - name: util-common-service
          image: hswagh9/util-common-service-docker-image # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8095 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: util-common-service
spec:
  selector:
    app: util-common-service
  ports:
    - protocol: "TCP"
      port: 8095 # The port that the service is running on in the cluster
      targetPort: 8095 # The port exposed by the service
  type: NodePort # type of the service.